services:
  smartshelf.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  smartshelf.dashboard:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  smartshelf.simulator:
    environment:
      DOTNET_ENVIRONMENT: Development
